package com.example.cuidapet.ui.screens.pets.models.enums

enum class Species(val label: String) {
    DOG("Cachorro"),
    CAT("Gato"),
    RABBIT("Coelho"),
    HAMSTER("Hamster"),
    GUINEA_PIG("Porquinho-da-Índia"),
    FERRET("Furão"),
    BIRD("Pássaro"),
    PARROT("Papagaio"),
    PARAKEET("Periquito"),
    CANARY("Canário"),
    TURTLE("Tartaruga"),
    TORTOISE("Jabuti"),
    SNAKE("Cobra"),
    LIZARD("Lagarto"),
    IGUANA("Iguana"),
    FISH("Peixe"),
    BETTA("Peixe Betta"),
    GOLDFISH("Peixe Dourado"),
    HORSE("Cavalo"),
    DONKEY("Burro"),
    PIG("Porco"),
    GOAT("Cabra"),
    SHEEP("Ovelha"),
    COW("Vaca"),
    CHICKEN("Galinha"),
    DUCK("Pato"),
    GOOSE("Ganso"),
    FROG("Sapo"),
    HEDGEHOG("Ouriço"),
    OTHER("Outro");
}
